# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  default

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'charankumarcpl/pipeline:$(Build.BuildId)'

steps:
# - task: Docker@2
#   displayName: Build an image
#   inputs:
#     command: build
#     dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
#     tags: |
#       $(tag)
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhubconnection'
    repository: 'charankumarcpl/pipeline'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhubconnection'
    repository: 'charankumarcpl/pipeline'
    command: 'push'

# - task: Docker@2
#   displayName: Build and Push an image
#   inputs:
#     containerRegistry: 'docker connection'
#     repository: 'reddyrani/jsimages'
#     command: 'buildAndPush'
#     Dockerfile: 'app/Dockerfile'
#     tags: '$(tag)'