# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- phani-dev

pool:
  default

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'charankumarcpl/pipeline'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'charankumarcpl/pipeline'
    command: 'push'